### ISSUE TITLE
This is awesome! But how do you use it?

### ISSUE THREAD

**Issue by expelledboy** [rvolosatovs/nixelium#3]
Hey man, love this repo. By any chance do you know Will Fancher? He [described](https://t.co/74V6R2vAJ5?amp=1) something very similar to what you have here.

I am new to nix, and dont know much about nixops. You think you give me a breakdown of how I might be able to adopt and start using your config?

**Comment by rvolosatovs** [comment]
Hello,
Thank you for the kind words!

Somehow I missed notification about this issue, so sorry for late reply.

> By any chance do you know Will Fancher? He [described](https://t.co/74V6R2vAJ5?amp=1) something very similar to what you have here.

No, I (unfortunately?) don't. The structure of this repo is just something I came up with eventually after some trial and error. The focus is on portability and interoperability. In a perfect world, I could use NixOps to provision servers, where I don't have `root` access(i.e. only a user account) or e.g. Mac machines, but that's not possible today, so I structured this in such a way that I could use just parts of this if necessary(e.g. just plain `home-manager` on a remote machine I don't have `root` on)

I have recently added a very brief ["usage" section](https://github.com/rvolosatovs/infrastructure#usage), which you might be interested in.

In terms of dependencies: stuff in `/nixops` depends on stuff in `/vendor/secrets/nixops` and `/nixos`, and similarly, stuff in `/nixos` depends on stuff in `/vendor/secrets/nixos` and `/home`, etc.

`/nixops/networks/private` contains the `private` network (consisting of my laptop and 2 servers for now), which is used by `nixops`.

In terms of adopting and using, you can replicate the structure and then adjust host configurations, `/resources` and "profile" configurations(see https://github.com/rvolosatovs/infrastructure/blob/b75f5d60d07aa041d8da4677e66d9676226f7258/nixos/profiles/laptop/default.nix for example)

NOTE: I've not been using the Mac for a while, so that's not actively maintained now

**Comment by rvolosatovs** [comment]
it's been a while, so I'm going to close this issue
